### ISSUE TITLE
undefined method `push' for some inexistent ObjectId

### ISSUE THREAD

**Issue by tirdadc** [mongoid/mongoid#3708]
I don't know what exactly changed but I initially suspected it to be related to the fact that mongoid wasn't pegged to a specific version in my Gemfile:

```gem 'mongoid', :github => 'mongoid/mongoid'```

But that seems to be contradicted by the fact that I have the same blob for mongoid in my Gemfile.lock between a working branch and one that doesn't:

```
GIT
  remote: git://github.com/mongoid/mongoid.git
  revision: 88599cf64c3d6df9a1277178ced69cd45d30c2f1
  specs:
    mongoid (4.0.0)
      activemodel (~> 4.0.0)
      moped (~> 1.5)
      origin (~> 1.0)
      tzinfo (~> 0.3.22)
```

But now my updates fail with this error, and I checked the ObjectId (53ac812f6912f701ba000001) and it doesn't correspond to anything in mongo:

```
> db.orders.find({_id: ObjectId("53ac812f6912f701ba000001")})
>
```
What's going on here?

```
/home/panic/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands/runner.rb:53:in `eval': undefined method `push' for "53ac812f6912f701ba000001":Moped::BSON::ObjectId (NoMethodError)
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/pushable.rb:54:in `each'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/pushable.rb:54:in `block (2 levels) in push'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable.rb:165:in `block in process_atomic_operations'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable.rb:163:in `each'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable.rb:163:in `process_atomic_operations'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/pushable.rb:51:in `block in push'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable.rb:141:in `prepare_atomic_operation'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/pushable.rb:50:in `push'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/atomic/modifiers.rb:122:in `block in add_operation'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/atomic/modifiers.rb:121:in `each'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/atomic/modifiers.rb:121:in `add_operation'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/atomic/modifiers.rb:87:in `block in set'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/atomic/modifiers.rb:84:in `each_pair'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/atomic/modifiers.rb:84:in `set'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/atomic.rb:353:in `generate_atomic_updates'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/atomic.rb:134:in `block in atomic_updates'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/atomic.rb:132:in `each'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/atomic.rb:132:in `atomic_updates'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/updatable.rb:119:in `init_atomic_updates'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/updatable.rb:25:in `block in update_document'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/updatable.rb:143:in `block (2 levels) in prepare_update'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:383:in `_run__1066962723__update__callbacks'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/interceptable.rb:132:in `run_callbacks'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/updatable.rb:142:in `block in prepare_update'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:373:in `_run__1066962723__save__callbacks'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/interceptable.rb:132:in `run_callbacks'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/updatable.rb:141:in `prepare_update'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/updatable.rb:24:in `update_document'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/savable.rb:25:in `save'
        from /home/panic/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/updatable.rb:78:in `update'
        from /var/www/project/redacted/app/models/order.rb:207:in `update_attributes'
```

**Comment by arthurnn** [comment]
I am not sure how to simulate this.
Can you test this against latest master and report back if it is still a problem?
Also if you could try to isolate the problem in a unit test, would be helpful. Try using this as base https://github.com/mongoid/mongoid/blob/master/examples/mongoid_test.rb.
thanks
