### ISSUE TITLE
comparison of Fixnum with nil failed

### ISSUE THREAD

**Issue by newdark** [mongoid/mongoid#3912]
Been Trying to delete this user but keeps bugging out on me. Can't figure out why. 

Is there a way around this problem? If more information need I can provide. 
```ruby
# If object exists then compare the two, otherwise return false
#
# @example Determine if we can compare.
#   matcher.determine("test", "$in")
#
# @param [ Object ] value The value to compare with.
# @param [ Symbol, String ] operator The comparison operation.
#
# @return [ true, false ] The comparison or false.
#
# @since 1.0.0
  def determine(value, operator)
    puts value
    puts operator
    attribute.__array__.any? {|attr|
      attr ? attr.send(operator, first(value)) : false
    }
  end

```
Here is the out put I get with the code I I am using above
```ruby
> id = '54909ce4752d71293e320900'
> user = User.where(id: id).first
2.0.0 :010 > user.delete
{"$gt"=>1}
>
{"$gt"=>1}
>
{"$gt"=>1}
>
{"$gt"=>1}
>
{"$gt"=>1}
>
{"$gt"=>1}
>
{"$gt"=>1}
>
{"$gt"=>1}
>
{"$gt"=>1}
>
{"$gt"=>nil}
>
{"$gt"=>nil}
>
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/matchable/default.rb:69:in `>'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/matchable/default.rb:69:in `block in determine'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/matchable/default.rb:68:in `each'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/matchable/default.rb:68:in `any?'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/matchable/default.rb:68:in `determine'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/matchable/gt.rb:17:in `matches?'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/matchable.rb:58:in `block (2 levels) in matches?'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/matchable.rb:57:in `each'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/matchable.rb:57:in `block in matches?'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/matchable.rb:55:in `each_pair'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/matchable.rb:55:in `matches?'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/contextual/memory.rb:152:in `block in initialize'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/contextual/memory.rb:149:in `select'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/contextual/memory.rb:149:in `initialize'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/contextual.rb:53:in `new'
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/contextual.rb:53:in `create_context'
... 25 levels...
from /path/toshared/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/persistable/deletable.rb:23:in `delete'
from (irb):10
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/commands/console.rb:90:in `start'
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/commands/console.rb:9:in `start'
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:69:in `console'
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/app_rails_loader.rb:43:in `require'
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/app_rails_loader.rb:43:in `block in exec_app_rails'
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/app_rails_loader.rb:32:in `loop'
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/app_rails_loader.rb:32:in `exec_app_rails'
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/cli.rb:5:in `<top (required)>'
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/bin/rails:9:in `require'
from /path/toshared/bundle/ruby/2.0.0/gems/railties-4.1.6/bin/rails:9:in `<top (required)>'
from /path/toshared/bundle/ruby/2.0.0/bin/rails:23:in `load'
from /path/toshared/bundle/ruby/2.0.0/bin/rails:23:in `<main>'2.0.0 :011 > exit
```

**Comment by newdark** [comment]
Placed this in the wrong github repo

**Comment by newdark** [comment]
Sorry Clicked close button by mistake.

**Comment by durran** [comment]
Can you please provide your `User` model?

**Comment by newdark** [comment]
Yes sure it is nothing uniq it is just a simple document with a id. tried to keep it super simple so as to reduce the total number of bugs that can happen. Really it is a hard bug to get to happen and I just call destroy in those cases. 

```ruby
class User
  include Mongoid::Document
  include Mongoid::Timestamps
end
```
