### ISSUE TITLE
MongoLab using underscore for username and database name in heroku

### ISSUE THREAD

**Issue by donnykurnia** [mongoid/mongoid#3921]
MongoLab that provide Mongo in Heroku set username and database name using underscore:

    heroku config:get MONGOLAB_URI
    mongodb://heroku_app33263013:7vuv9mai25mcb8c8ga4mrod3am@ds031611.mongolab.com:31611/heroku_app33263013

I got this error when using mongoid-4.0.0:

    $ heroku run rails c
    Running `rails c` attached to terminal... up, run.5702
    Loading production environment (Rails 4.0.5)
    irb(main):001:0> PageSetting
    => PageSetting
    irb(main):002:0> PageSetting.count
    NoMethodError: undefined method `[]' for nil:NilClass
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/sessions/mongo_uri.rb:25:in `database'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/sessions/mongo_uri.rb:73:in `to_hash'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/sessions/factory.rb:106:in `parse'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/sessions/factory.rb:62:in `create_session'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/sessions/factory.rb:28:in `create'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/sessions.rb:65:in `with_name'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/sessions.rb:105:in `mongo_session'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/sessions.rb:121:in `collection'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/sessions/options.rb:161:in `method_missing'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:263:in `initialize'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/contextual.rb:53:in `new'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/contextual.rb:53:in `create_context'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/contextual.rb:35:in `context'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/contextual.rb:19:in `count'
            from /app/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/findable.rb:51:in `count'
            from (irb):2
            from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.0.5/lib/rails/commands/console.rb:90:in `start'
            from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.0.5/lib/rails/commands/console.rb:9:in `start'
            from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.0.5/lib/rails/commands.rb:62:in `<top (required)>'
            from /app/bin/rails:4:in `require'
            from /app/bin/rails:4:in `<main>'irb(main):003:0>

I see that in file `lib/mongoid/sessions/mongo_uri.rb`, the `user` and `database` only expected to be word -, so the underscore in MONGOLAB_URI cause the errors above.

**Comment by donnykurnia** [comment]
Sorry, the errors is in my config.
