### ISSUE TITLE
Stuck indefinitely on Moped connection read

### ISSUE THREAD

**Issue by ashrestha91** [mongoid/mongoid#3925]
I'm using sidekiq with mongoid, and am seeing some workers get stuck.  They don't error out, they're just hung.  The sidekiq thread dump gives the following:
```
/usr/local/bundle/gems/moped-2.0.3/lib/moped/connection/socket/connectable.rb:47:in `read'
/usr/local/bundle/gems/moped-2.0.3/lib/moped/connection/socket/connectable.rb:47:in `block in read'
/usr/local/bundle/gems/moped-2.0.3/lib/moped/connection/socket/connectable.rb:119:in `handle_socket_errors'
/usr/local/bundle/gems/moped-2.0.3/lib/moped/connection/socket/connectable.rb:47:in `read'
/usr/local/bundle/gems/moped-2.0.3/lib/moped/connection.rb:194:in `read_data'
/usr/local/bundle/gems/moped-2.0.3/lib/moped/connection.rb:130:in `block in read'
/usr/local/bundle/gems/moped-2.0.3/lib/moped/connection.rb:224:in `with_connection'
/usr/local/bundle/gems/moped-2.0.3/lib/moped/connection.rb:114:in `read'
```

We typically see 1 or 2 workers out of a few hundred thousand have this issue each day.  If we restart the workers/service the workers usually succeed.

**Comment by arthurnn** [comment]
thats a moped issue, you open a ticket there and close it in here..
thanks
