### ISSUE TITLE
Mongoid is blocked when mongo server restart

### ISSUE THREAD

**Issue by rkyrychuk** [mongoid/mongoid#4093]
Mongoid is totally blocked when server restarts.
Looks like timeout option is not working.
```RUBY
# Gemfile
gem 'mongoid', github: "mongoid/mongoid", branch: "master"
```

```RUBY 
#mongo_test.rb
require 'mongoid'
class Product
  include Mongoid::Document
  field :name,  type: String
end

Mongoid.load! "mongoid.yml", :development
Product.destroy_all
Product.create(name: "Mongo test")

while true
  print Product.all.first.name
  sleep 1
end
```
```YAML
#mongoid.yml
development:
  clients:
    default:
      uri: "mongodb://localhost/mongo_test"
      options:
        read:
          mode: :primary
        server_selection_timeout: 10
        socket_timeout: 5
```
When mongo server restart, code just blocked, not reconnects, no errors.

Stacktrace on break:
```
, [2015-06-08T13:13:54.522779 #31341] DEBUG -- : MONGODB | QUERY | namespace=mongo_test.products selector={} flags=[] limit=0 skip=0 project=nil | runtime: 158644.8395ms
D, [2015-06-08T13:13:54.523294 #31341] DEBUG -- : MONGODB | COMMAND | namespace=admin.$cmd selector={:ismaster=>1} flags=[] limit=-1 skip=0 project=nil | runtime: 151666.8334ms
/home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/socket.rb:161:in `read': Interrupt
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/socket.rb:161:in `read_from_socket'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/socket.rb:126:in `block in read'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/socket.rb:173:in `handle_errors'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/socket.rb:123:in `read'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/protocol/serializers.rb:62:in `deserialize'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/protocol/message.rb:193:in `deserialize_header'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/protocol/message.rb:83:in `deserialize'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/server/connectable.rb:110:in `block in read'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/server/connectable.rb:95:in `ensure_connected'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/server/connectable.rb:110:in `read'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/server/connectable.rb:67:in `block in dispatch'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/loggable.rb:44:in `log'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/loggable.rb:65:in `log_debug'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/server/connectable.rb:65:in `dispatch'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/operation/read/query.rb:61:in `block in execute_message'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/server/connection_pool.rb:99:in `with_connection'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/server/context.rb:63:in `with_connection'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/operation/read/query.rb:60:in `execute_message'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/operation/read/query.rb:54:in `execute'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/collection/view.rb:164:in `send_initial_query'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mongo-2.0.4/lib/mongo/collection/view/iterable.rb:39:in `each'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/mongoid-2f806d1d38b4/lib/mongoid/query_cache.rb:207:in `each'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/mongoid-2f806d1d38b4/lib/mongoid/contextual/mongo.rb:240:in `first'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/mongoid-2f806d1d38b4/lib/mongoid/contextual/mongo.rb:240:in `block in first'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/mongoid-2f806d1d38b4/lib/mongoid/contextual/mongo.rb:489:in `try_cache'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/mongoid-2f806d1d38b4/lib/mongoid/contextual/mongo.rb:239:in `first'
	from /home/vagrant/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/mongoid-2f806d1d38b4/lib/mongoid/contextual.rb:20:in `first'
	from ./mongo_test.rb:12:in `<main>'
```

**Comment by durran** [comment]
What environment is this? I'm getting the expected with this code.

```
/Users/modetojoy/.rvm/gems/ruby-2.2.0@mongoid-test/gems/mongo-2.0.4/lib/mongo/socket.rb:177:in `rescue in handle_errors': Connection reset by peer (Mongo::Error::SocketError)
	from /Users/modetojoy/.rvm/gems/ruby-2.2.0@mongoid-test/gems/mongo-2.0.4/lib/mongo/socket.rb:172:in `handle_errors'
```

**Comment by durran** [comment]
And how are you restarting the server? Just killing it and bringing it back up?

**Comment by rkyrychuk** [comment]
ubuntu 12.04, 
mongodb  server is on docker, mongo is mongodb 3.0 (wiredTiger)
I just stopped, wait 2-3 seconds and started.

**Comment by rkyrychuk** [comment]
Full configuration: 
Server 1. Ubuntu 14.04, Ruby (2.1.3p242), mongoid master
Server 2. Ubuntu 14.04, docker, mongo 3 (WiredTiger)

I start getting blocking messages after mongo was killed, and reproduced by restarting docker mongo process

**Comment by rkyrychuk** [comment]
Did some test.
1. Issue is reproduced only on virtualbox. When db or ruby code or both is on virtualbox.
When using real server get connection reset by peer.
2. Still expect to have at least timeout error, as soon as it is not working here, it may not working in other places.

**Comment by rkyrychuk** [comment]
3. Issue reproduced also with docker without virtualbox

**Comment by durran** [comment]
Why are you expecting a timeout error? Are you expecting Mongoid to be catching the connection reset and retrying? We don't have any retry logic in Mongoid at the moment.

**Comment by rkyrychuk** [comment]
I expect timeout error, because I've set socket_timeout in mongoid.yml. 

Just want to ensure that if something unexpected will happen, It just fail instead of blocking whole server.
For the moment, if you have web app, and mongo node will fail (Out of memory killer for example) or restart, it totally block whole web server process and only web server restart is required to unblock.

**Comment by rkyrychuk** [comment]
Actually I've set 2 timeouts

server_selection_timeout: 10
socket_timeout: 5

and nothing worked

**Comment by durran** [comment]
Can you try updating the `mongo` gem to 2.0.5 and see if this persists? There were some networking fixes in this release that I would like to see if they change anything.

**Comment by rkyrychuk** [comment]
Ok, will test

**Comment by rkyrychuk** [comment]
Got IOError (Mongo::Error::SocketError). It is totally ok.
So, issue can be closed, right?

**Comment by durran** [comment]
Excellent - thanks!
